[project]
name = "dreadbeat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "bleak>=1.0.1",
]

[tool.setuptools]
packages = ["src", "config",]
